"use strict";

/**
 * src/main/movies/sample.ts
 *
 * L4 内置示例数据（兜底链最后一级）.
 * 所有条目 isSample=true，渲染层显示「示例」徽标.
 * 字段形态对齐 MovieItem，无需网络/key.
 */

import { SOURCE } from "./types";

const SAMPLE_POSTER = "https://picsum.photos/seed/__ID__/300/420";

function poster(id: string): string {
  return SAMPLE_POSTER.replace("__ID__", id);
}

const NOW_PLAYING: any[] = [
  {
    id: "s1",
    title: "星海远征",
    enTitle: "Starbound",
    rating: 8.6,
    poster: poster("s1"),
    showInfo: "今日 1280 家影院 8600 场",
    releaseDate: "2026-08-12",
    star: "林深, 苏晚, 陈牧",
    genres: ["科幻", "冒险"],
    durationMin: 142,
    summary: "一支深空探索队在未知星域遭遇文明遗迹，关于勇气与抉择的星际史诗。",
    director: "陆远",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "s2",
    title: "盛夏告白",
    enTitle: "Midsummer Confession",
    rating: 7.9,
    poster: poster("s2"),
    showInfo: "今日 960 家影院 5200 场",
    releaseDate: "2026-08-08",
    star: "周可可, 高屿",
    genres: ["爱情", "青春"],
    durationMin: 108,
    summary: "两个高中同桌在毕业暑假里，把藏了三年的话终于说出口。",
    director: "叶知秋",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "s3",
    title: "暗潮",
    enTitle: "Undertow",
    rating: 8.1,
    poster: poster("s3"),
    showInfo: "今日 740 家影院 4100 场",
    releaseDate: "2026-08-15",
    star: "马骏, 白薇",
    genres: ["悬疑", "犯罪"],
    durationMin: 126,
    summary: "一桩海边小镇的失踪案，牵出被潮水掩盖多年的秘密。",
    director: "韩松",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "s4",
    title: "机甲纪元",
    enTitle: "Mecha Era",
    rating: 7.5,
    poster: poster("s4"),
    showInfo: "今日 880 家影院 6000 场",
    releaseDate: "2026-07-30",
    star: "赵岩, 林夕",
    genres: ["动作", "科幻"],
    durationMin: 135,
    summary: "人类与智能机甲并肩作战，守卫最后一座浮空城市。",
    director: "雷克",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "s5",
    title: "山野来信",
    enTitle: "Letters from the Hills",
    rating: 8.8,
    poster: poster("s5"),
    showInfo: "今日 520 家影院 2600 场",
    releaseDate: "2026-08-01",
    star: "宋词, 田螺",
    genres: ["剧情", "文艺"],
    durationMin: 118,
    summary: "一位归乡青年用一年时间，记录下逐渐老去的小山村。",
    director: "顾长亭",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "s6",
    title: "萌宠大作战",
    enTitle: "Pet Squad",
    rating: 7.2,
    poster: poster("s6"),
    showInfo: "今日 700 家影院 3800 场",
    releaseDate: "2026-08-10",
    star: "配音：糖糖, 豆豆",
    genres: ["喜剧", "动画"],
    durationMin: 92,
    summary: "一群走丢的小动物在城里组队，展开一场爆笑回家冒险。",
    director: "王泡泡",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "s7",
    title: "无声证词",
    enTitle: "Silent Testimony",
    rating: 8.3,
    poster: poster("s7"),
    showInfo: "今日 610 家影院 3300 场",
    releaseDate: "2026-08-18",
    star: "江临, 沈默",
    genres: ["犯罪", "剧情"],
    durationMin: 121,
    summary: "一位失语证人，用画笔还原了无人相信的真相。",
    director: "冯岸",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "s8",
    title: "味觉奇旅",
    enTitle: "Flavor Quest",
    rating: 7.7,
    poster: poster("s8"),
    showInfo: "今日 450 家影院 2400 场",
    releaseDate: "2026-08-05",
    star: "米小满, 罗锅",
    genres: ["喜剧", "美食"],
    durationMin: 104,
    summary: "一家濒临倒闭的小馆，靠一道祖传秘方重新点燃街坊烟火。",
    director: "汤司令",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
];

const COMING: any[] = [
  {
    id: "c1",
    title: "霜降之城",
    enTitle: "City of Frost",
    rating: undefined,
    poster: poster("c1"),
    wish: 382000,
    comingTitle: "9月5日 全国上映",
    showState: "预售",
    releaseDate: "2026-09-05",
    star: "萧寒, 唐果",
    genres: ["奇幻", "冒险"],
    summary: "当第一场霜降临，沉睡百年的守护兽即将苏醒。",
    director: "北野",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "c2",
    title: "追光的人",
    enTitle: "Light Chaser",
    rating: undefined,
    poster: poster("c2"),
    wish: 256000,
    comingTitle: "9月12日 全国上映",
    showState: "待映",
    releaseDate: "2026-09-12",
    star: "程光, 安琪",
    genres: ["剧情", "励志"],
    summary: "一个山村女孩，用一盏灯照亮了整个村子的未来。",
    director: "禾木",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "c3",
    title: "代号：归途",
    enTitle: "Operation Homecoming",
    rating: undefined,
    poster: poster("c3"),
    wish: 511000,
    comingTitle: "9月19日 全国上映",
    showState: "预售",
    releaseDate: "2026-09-19",
    star: "秦野, 罗盘",
    genres: ["动作", "战争"],
    summary: "撤侨行动中，一支小队护送同胞穿越火线回家。",
    director: "沙海",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "c4",
    title: "云端恋曲",
    enTitle: "Cloud Romance",
    rating: undefined,
    poster: poster("c4"),
    wish: 198000,
    comingTitle: "9月26日 全国上映",
    showState: "待映",
    releaseDate: "2026-09-26",
    star: "夏沫, 云帆",
    genres: ["爱情", "音乐"],
    summary: "两个在万米高空相遇的陌生人，用一首歌记住了彼此。",
    director: "风间",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "c5",
    title: "怪兽幼稚园",
    enTitle: "Monster Kindergarten",
    rating: undefined,
    poster: poster("c5"),
    wish: 144000,
    comingTitle: "10月1日 全国上映",
    showState: "待映",
    releaseDate: "2026-10-01",
    star: "配音：团子, 球球",
    genres: ["动画", "喜剧"],
    summary: "一群小怪兽上幼儿园的第一天，比想象中更吵闹也更温暖。",
    director: "毛球",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
  {
    id: "c6",
    title: "时间的形状",
    enTitle: "The Shape of Time",
    rating: undefined,
    poster: poster("c6"),
    wish: 673000,
    comingTitle: "10月8日 全国上映",
    showState: "想看榜第一",
    releaseDate: "2026-10-08",
    star: "时砚, 简宁",
    genres: ["科幻", "悬疑"],
    summary: "如果时间可以被折叠，你愿意回到哪一个瞬间？",
    director: "钟慢",
    source: SOURCE.SAMPLE,
    isSample: true,
  },
];

/** 返回内置示例 payload（L4 兜底，渲染层标「示例」徽标） */
export function getMoviesSample(): any {
  return {
    ok: true,
    nowPlaying: NOW_PLAYING.map((m) => ({ ...m })),
    coming: COMING.map((m) => ({ ...m })),
    fetchedAt: Date.now(),
    source: SOURCE.SAMPLE,
  };
}

module.exports = { getMoviesSample, NOW_PLAYING, COMING };
