/**
 * src/renderer/worldcup/squads-data.js
 *
 * v2.9.6 — 48 队 26 人大名单 (完整, FIFA 2026 报名)
 *
 * 数据来源: FlashscoreUSA 1248 players (2026-06 公布, 截止 2026-06-02)
 * 队名映射: 跟 teams-data.js FIFA 官方名 1:1
 *   - 'Czech Republic' (Flashscore) → 'Czechia' (FIFA)
 *   - 'Cape Verde' (Flashscore) → 'Cabo Verde' (FIFA)
 *   - 'Iran' (Flashscore) → 'IR Iran' (FIFA)
 *   - 'D.R. Congo' (Flashscore) → 'Congo DR' (FIFA)
 *   - 'Türkiye' 跟 Flashscore 'Turkey' 同队, 走 FIFA 名
 *
 * 阵型 4-3-3 通用 (GK 3 + DF 9/10 + MF 7/8 + FW 4/6)
 * 注: 各队报名 23-26 人不等, 3 GK 必备. 队实际报名人数标在每队注释.
 *
 * Schema: [{ number, position, name, club }]
 */

const SQUADS = {
  // ─── Group A (4 队) ─────────────────────────────
  // Czech Republic — 26 人
  Czechia: [
    // GK
    { number: 1,  position: 'GK', name: 'Lucas Hornicek',       club: 'Braga' },
    { number: 2,  position: 'GK', name: 'Jindrich Stanek',       club: 'Slavia Prague' },
    { number: 3,  position: 'GK', name: 'Matej Kovar',           club: 'PSV' },
    // DF
    { number: 4,  position: 'DF', name: 'Vladimir Coufal',       club: 'Hoffenheim' },
    { number: 5,  position: 'DF', name: 'David Doudera',         club: 'Slavia Prague' },
    { number: 6,  position: 'DF', name: 'Tomas Holes',           club: 'Slavia Prague' },
    { number: 7,  position: 'DF', name: 'Robin Hranac',          club: 'Hoffenheim' },
    { number: 8,  position: 'DF', name: 'Stepan Chaloupek',      club: 'Slavia Prague' },
    { number: 9,  position: 'DF', name: 'David Jurasek',         club: 'Slavia Prague' },
    { number: 10, position: 'DF', name: 'Ladislav Krejci',       club: 'Wolves' },
    { number: 11, position: 'DF', name: 'Jaroslav Zeleny',       club: 'Sparta Prague' },
    { number: 12, position: 'DF', name: 'David Zima',            club: 'Slavia Prague' },
    // MF
    { number: 13, position: 'MF', name: 'Lukas Cerv',            club: 'Viktoria Plzen' },
    { number: 14, position: 'MF', name: 'Vladimir Darida',       club: 'Hradec Kralove' },
    { number: 15, position: 'MF', name: 'Lukas Provod',          club: 'Slavia Prague' },
    { number: 16, position: 'MF', name: 'Michal Sadilek',        club: 'Slavia Prague' },
    { number: 17, position: 'MF', name: 'Hugo Sochurek',         club: 'Sparta Prague' },
    { number: 18, position: 'MF', name: 'Alexandr Sojka',        club: 'Viktoria Plzen' },
    { number: 19, position: 'MF', name: 'Tomas Soucek',          club: 'West Ham' },
    { number: 20, position: 'MF', name: 'Pavel Sulc',            club: 'Lyon' },
    { number: 21, position: 'MF', name: 'Denis Visinsky',        club: 'Viktoria Plzen' },
    // FW
    { number: 22, position: 'FW', name: 'Adam Hlozek',           club: 'Hoffenheim' },
    { number: 23, position: 'FW', name: 'Tomas Chory',           club: 'Slavia Prague' },
    { number: 24, position: 'FW', name: 'Mojmir Chytil',         club: 'Slavia Prague' },
    { number: 25, position: 'FW', name: 'Jan Kuchta',            club: 'Sparta Prague' },
    { number: 26, position: 'FW', name: 'Patrik Schick',         club: 'Bayer Leverkusen' },
  ],
  // Mexico — 25 人
  Mexico: [
    { number: 1,  position: 'GK', name: 'Carlos Acevedo',        club: 'Santos Laguna' },
    { number: 2,  position: 'GK', name: 'Guillermo Ochoa',       club: 'AEL Limassol' },
    { number: 3,  position: 'GK', name: 'Raul Rangel',           club: 'Chivas' },
    { number: 4,  position: 'DF', name: 'Mateo Chavez',          club: 'AZ' },
    { number: 5,  position: 'DF', name: 'Jesus Gallardo',        club: 'Toluca' },
    { number: 6,  position: 'DF', name: 'Cesar Montes',          club: 'Lokomotiv Moscow' },
    { number: 7,  position: 'DF', name: 'Israel Reyes',          club: 'Club America' },
    { number: 8,  position: 'DF', name: 'Jorge Sanchez',         club: 'PAOK' },
    { number: 9,  position: 'DF', name: 'Johan Vasquez',         club: 'Genoa' },
    { number: 10, position: 'MF', name: 'Roberto Alvarado',      club: 'Chivas' },
    { number: 11, position: 'MF', name: 'Edson Alvarez',         club: 'Fenerbahce' },
    { number: 12, position: 'MF', name: 'Luis Chavez',           club: 'Dinamo Moscow' },
    { number: 13, position: 'MF', name: 'Alvaro Fidalgo',        club: 'Real Betis' },
    { number: 14, position: 'MF', name: 'Brian Gutierrez',       club: 'Chivas' },
    { number: 15, position: 'MF', name: 'Erik Lira',             club: 'Cruz Azul' },
    { number: 16, position: 'MF', name: 'Gilberto Mora',         club: 'Club Tijuana' },
    { number: 17, position: 'MF', name: 'Orbelin Pineda',        club: 'AEK Athens' },
    { number: 18, position: 'MF', name: 'Luis Romo',             club: 'Chivas' },
    { number: 19, position: 'MF', name: 'Obed Vargas',           club: 'Atletico Madrid' },
    { number: 20, position: 'FW', name: 'Santiago Gimenez',      club: 'Milan' },
    { number: 21, position: 'FW', name: 'Armando Gonzalez',      club: 'Chivas' },
    { number: 22, position: 'FW', name: 'Cesar Huerta',          club: 'Anderlecht' },
    { number: 23, position: 'FW', name: 'Raul Jimenez',          club: 'Fulham' },
    { number: 24, position: 'FW', name: 'Julian Quinones',       club: 'Al Qadsiyah' },
    { number: 25, position: 'FW', name: 'Alexis Vega',           club: 'Toluca' },
  ],
  // South Africa — 26 人
  'South Africa': [
    { number: 1,  position: 'GK', name: 'Sipho Chaine',          club: 'Orlando Pirates' },
    { number: 2,  position: 'GK', name: 'Ricardo Goss',          club: 'Siwelele' },
    { number: 3,  position: 'GK', name: 'Ronwen Williams',       club: 'Mamelodi Sundowns' },
    { number: 4,  position: 'DF', name: 'Bradley Cross',         club: 'Kaizer Chiefs' },
    { number: 5,  position: 'DF', name: 'Samukelo Kabini',       club: 'Molde' },
    { number: 6,  position: 'DF', name: 'Olwethu Makhanya',      club: 'Philadelphia Union' },
    { number: 7,  position: 'DF', name: 'Thabang Matuludi',      club: 'Polokwane City' },
    { number: 8,  position: 'DF', name: 'Mbekezeli Mbokazi',     club: 'Chicago Fire' },
    { number: 9,  position: 'DF', name: 'Aubrey Modiba',         club: 'Mamelodi Sundowns' },
    { number: 10, position: 'DF', name: 'Khuliso Mudau',         club: 'Mamelodi Sundowns' },
    { number: 11, position: 'DF', name: 'Khulumani Ndamane',     club: 'Mamelodi Sundowns' },
    { number: 12, position: 'DF', name: 'Ime Okun',              club: 'Hannover 96' },
    { number: 13, position: 'DF', name: 'Nkosinathi Sibisi',     club: 'Orlando Pirates' },
    { number: 14, position: 'MF', name: 'Jayden Adams',          club: 'Mamelodi Sundowns' },
    { number: 15, position: 'MF', name: 'Thalente Mbatha',       club: 'Orlando Pirates' },
    { number: 16, position: 'MF', name: 'Teboho Mokoena',        club: 'Mamelodi Sundowns' },
    { number: 17, position: 'MF', name: 'Sphephelo Sithole',     club: 'Tondela' },
    { number: 18, position: 'FW', name: 'Oswin Appollis',        club: 'Orlando Pirates' },
    { number: 19, position: 'FW', name: 'Lyle Foster',           club: 'Burnley' },
    { number: 20, position: 'FW', name: 'Evidence Makgopa',      club: 'Orlando Pirates' },
    { number: 21, position: 'FW', name: 'Iqraam Rayners',        club: 'Mamelodi Sundowns' },
    { number: 22, position: 'FW', name: 'Thapelo Maseko',        club: 'AEL Limassol' },
    { number: 23, position: 'FW', name: 'Relobohile Mofokeng',   club: 'Orlando Pirates' },
    { number: 24, position: 'FW', name: 'Tshepang Moremi',       club: 'Orlando Pirates' },
    { number: 25, position: 'FW', name: 'Kamogelo Sebelebele',   club: 'Orlando Pirates' },
    { number: 26, position: 'FW', name: 'Themba Zwane',          club: 'Mamelodi Sundowns' },
  ],
  // South Korea — 25 人
  'Korea Republic': [
    { number: 1,  position: 'GK', name: 'Kim Seung-Gyu',         club: 'FC Tokyo' },
    { number: 2,  position: 'GK', name: 'Song Bum-Keun',         club: 'Jeonbuk' },
    { number: 3,  position: 'GK', name: 'Jo Hyeon-Woo',          club: 'Ulsan Hyundai' },
    { number: 4,  position: 'DF', name: 'Kim Moon-Hwan',         club: 'Daejeon' },
    { number: 5,  position: 'DF', name: 'Kim Min-Jae',           club: 'Bayern Munich' },
    { number: 6,  position: 'DF', name: 'Kim Tae-Hyeon',         club: 'Kashima Antlers' },
    { number: 7,  position: 'DF', name: 'Park Jin-Seob',         club: 'Zhejiang Professional' },
    { number: 8,  position: 'DF', name: 'Seol Young-Woo',        club: 'Crvena zvezda' },
    { number: 9,  position: 'DF', name: 'Jens Castrop',          club: 'Borussia Monchengladbach' },
    { number: 10, position: 'DF', name: 'Lee Ki-Hyuk',           club: 'Gangwon' },
    { number: 11, position: 'DF', name: 'Lee Tae-Seok',          club: 'Austria Vienna' },
    { number: 12, position: 'DF', name: 'Lee Han-Beom',          club: 'FC Midtjylland' },
    { number: 13, position: 'DF', name: 'Cho Yu-Min',            club: 'Al Sharjah' },
    { number: 14, position: 'MF', name: 'Kim Jin-Gyu',           club: 'Jeonbok' },
    { number: 15, position: 'MF', name: 'Bae Jun-Ho',            club: 'Stoke City' },
    { number: 16, position: 'MF', name: 'Paik Seung-Ho',         club: 'Birmingham City' },
    { number: 17, position: 'MF', name: 'Yang Hyun-Jun',         club: 'Celtic' },
    { number: 18, position: 'MF', name: 'Eom Ji-Sung',           club: 'Swansea City' },
    { number: 19, position: 'MF', name: 'Lee Kang-In',           club: 'Paris Saint-Germain' },
    { number: 20, position: 'MF', name: 'Lee Dong-Gyeong',       club: 'Ulsan Hyundai' },
    { number: 21, position: 'MF', name: 'Lee Jae-Sung',          club: 'Mainz' },
    { number: 22, position: 'MF', name: 'Hwang In-Beom',         club: 'Feyenoord' },
    { number: 23, position: 'FW', name: 'Hwang Hee-Chan',        club: 'Wolves' },
    { number: 24, position: 'FW', name: 'Son Heung-Min',         club: 'Los Angeles FC' },
    { number: 25, position: 'FW', name: 'Oh Hyeon-Gyu',          club: 'Besiktas' },
  ],

  // ─── Group B (4 队) ─────────────────────────────
  // Bosnia & Herzegovina — 25 人
  'Bosnia & Herzegovina': [
    { number: 1,  position: 'GK', name: 'Nikola Vasilj',         club: 'St Pauli' },
    { number: 2,  position: 'GK', name: 'Martin Zlomislic',      club: 'Rijeka' },
    { number: 3,  position: 'GK', name: 'Osman Hadzikic',        club: 'Slaven Belupo' },
    { number: 4,  position: 'DF', name: 'Sead Kolasinac',        club: 'Atalanta' },
    { number: 5,  position: 'DF', name: 'Amar Dedic',            club: 'Benfica' },
    { number: 6,  position: 'DF', name: 'Nihad Mujakic',         club: 'Gaziantep' },
    { number: 7,  position: 'DF', name: 'Nikola Katic',          club: 'Schalke 04' },
    { number: 8,  position: 'DF', name: 'Tarik Muharemovic',     club: 'Sassuolo' },
    { number: 9,  position: 'DF', name: 'Stjepan Radeljic',      club: 'Rijeka' },
    { number: 10, position: 'DF', name: 'Dennis Hadzikadunic',   club: 'Sampdoria' },
    { number: 11, position: 'DF', name: 'Nidal Celik',           club: 'Lens' },
    { number: 12, position: 'MF', name: 'Amir Hadziahmetovic',   club: 'Hull City' },
    { number: 13, position: 'MF', name: 'Ivan Sunjic',           club: 'Pafos' },
    { number: 14, position: 'MF', name: 'Ivan Basic',            club: 'Astana' },
    { number: 15, position: 'MF', name: 'Dzenis Burnic',         club: 'Karlsruher SC' },
    { number: 16, position: 'MF', name: 'Ermin Mahmic',          club: 'Slovan Liberec' },
    { number: 17, position: 'MF', name: 'Benjamin Tahirovic',    club: 'Brondby' },
    { number: 18, position: 'MF', name: 'Amar Memic',            club: 'Viktoria Plzen' },
    { number: 19, position: 'MF', name: 'Armin Gigovic',         club: 'Young Boys' },
    { number: 20, position: 'MF', name: 'Kerim Alajbegovic',     club: 'RB Salzburg' },
    { number: 21, position: 'MF', name: 'Esmir Bajraktarevic',   club: 'PSV Eindhoven' },
    { number: 22, position: 'FW', name: 'Ermedin Demirovic',     club: 'VfB Stuttgart' },
    { number: 23, position: 'FW', name: 'Jovo Lukic',            club: 'Universitatea Cluj' },
    { number: 24, position: 'FW', name: 'Samed Bazdar',          club: 'Jagiellonia Bialystok' },
    { number: 25, position: 'FW', name: 'Edin Dzeko',            club: 'Schalke 04' },
  ],
  // Canada — 26 人
  Canada: [
    { number: 1,  position: 'GK', name: 'Dayne St. Clair',       club: 'Inter Miami' },
    { number: 2,  position: 'GK', name: 'Maxime Crepeau',        club: 'Orlando SC' },
    { number: 3,  position: 'GK', name: 'Owen Goodman',          club: 'Barnsley' },
    { number: 4,  position: 'DF', name: 'Alistair Johnston',     club: 'Celtic' },
    { number: 5,  position: 'DF', name: 'Derek Cornelius',       club: 'Rangers' },
    { number: 6,  position: 'DF', name: 'Ritchie Laryea',        club: 'Toronto FC' },
    { number: 7,  position: 'DF', name: 'Niko Sigur',            club: 'Hajduk Split' },
    { number: 8,  position: 'DF', name: 'Joel Waterman',         club: 'Chicago Fire' },
    { number: 9,  position: 'DF', name: 'Luc De Fougerolles',    club: 'Dender' },
    { number: 10, position: 'DF', name: 'Moise Bombito',         club: 'OGC Nice' },
    { number: 11, position: 'DF', name: 'Alphonso Davies',       club: 'Bayern Munich' },
    { number: 12, position: 'DF', name: 'Alfie Jones',           club: 'Middlesbrough' },
    { number: 13, position: 'MF', name: 'Stephen Eustaquio',     club: 'Los Angeles FC' },
    { number: 14, position: 'MF', name: 'Ismael Kone',           club: 'Sassuolo' },
    { number: 15, position: 'MF', name: 'Tajon Buchanan',        club: 'Villarreal' },
    { number: 16, position: 'MF', name: 'Mathieu Choiniere',     club: 'Los Angeles FC' },
    { number: 17, position: 'MF', name: 'Ali Ahmed',             club: 'Norwich City' },
    { number: 18, position: 'MF', name: 'Nathan Saliba',         club: 'Anderlecht' },
    { number: 19, position: 'MF', name: 'Liam Millar',           club: 'Hull City' },
    { number: 20, position: 'MF', name: 'Jayden Nelson',         club: 'Austin FC' },
    { number: 21, position: 'MF', name: 'Jacob Shaffelburg',     club: 'Los Angeles FC' },
    { number: 22, position: 'MF', name: 'Jonathan Osorio',       club: 'Toronto FC' },
    { number: 23, position: 'FW', name: 'Jonathan David',        club: 'Juventus' },
    { number: 24, position: 'FW', name: 'Cyle Larin',           club: 'Southampton' },
    { number: 25, position: 'FW', name: 'Tani Oluwaseyi',        club: 'Villarreal' },
    { number: 26, position: 'FW', name: 'Promise David',         club: 'Union Saint-Gilloise' },
  ],
  // Qatar — 26 人
  Qatar: [
    { number: 1,  position: 'GK', name: 'Mahmoud Abunada',       club: 'Al-Rayyan' },
    { number: 2,  position: 'GK', name: 'Meshaal Barsham',       club: 'Al-Sadd' },
    { number: 3,  position: 'GK', name: 'Salah Zakaria',         club: 'Al-Duhail' },
    { number: 4,  position: 'DF', name: 'Ayoub Al Alawi',        club: 'TBD' },
    { number: 5,  position: 'DF', name: 'Homam Al Amini',        club: 'Leonesa' },
    { number: 6,  position: 'DF', name: 'Sultan Al-Brake',       club: 'Al-Duhail' },
    { number: 7,  position: 'DF', name: 'Al Hashmi Al Hussain',  club: 'Al-Arabi' },
    { number: 8,  position: 'DF', name: 'Boualem Khoukhi',       club: 'Al-Sadd' },
    { number: 9,  position: 'DF', name: 'Issa Laye',             club: 'TBD' },
    { number: 10, position: 'DF', name: 'Lucas Mendes',          club: 'Al-Wakra' },
    { number: 11, position: 'DF', name: 'Pedro Miguel',          club: 'Al-Sadd' },
    { number: 12, position: 'MF', name: 'Karim Boudiaf',         club: 'Al-Duhail' },
    { number: 13, position: 'MF', name: 'Ahmed Fathi',           club: 'Al-Arabi' },
    { number: 14, position: 'MF', name: 'Jassim Gaber',          club: 'Al-Rayyan' },
    { number: 15, position: 'MF', name: 'Abdulaziz Hatem',       club: 'Al-Rayyan' },
    { number: 16, position: 'MF', name: 'Assim Madibo',          club: 'Al-Wakra' },
    { number: 17, position: 'MF', name: 'Mohammad Al Mannai',    club: 'Shamal' },
    { number: 18, position: 'FW', name: 'Hassan Al Haydos',      club: 'Al-Sadd' },
    { number: 19, position: 'FW', name: 'Ahmed Al Ganehi',       club: 'Al-Gharafa' },
    { number: 20, position: 'FW', name: 'Youssef Abdurisag',     club: 'Al-Wakra' },
    { number: 21, position: 'FW', name: 'Akram Afif',            club: 'Al-Sadd' },
    { number: 22, position: 'FW', name: 'Ahmed Alaaeldin',       club: 'Al-Rayyan' },
    { number: 23, position: 'FW', name: 'Almoez Ali',           club: 'Al-Duhail' },
    { number: 24, position: 'FW', name: 'Edmilson Junior',       club: 'Al-Duhail' },
    { number: 25, position: 'FW', name: 'Tahseen Mohammed',      club: 'Al-Duhail' },
    { number: 26, position: 'FW', name: 'Mohammed Muntari',      club: 'Al-Gharafa' },
  ],
  // Switzerland — 25 人
  Switzerland: [
    { number: 1,  position: 'GK', name: 'Marvin Keller',         club: 'Young Boys' },
    { number: 2,  position: 'GK', name: 'Gregor Kobel',          club: 'Borussia Dortmund' },
    { number: 3,  position: 'GK', name: 'Yvon Mvogo',            club: 'Lorient' },
    { number: 4,  position: 'DF', name: 'Manuel Akanji',         club: 'Inter Milan' },
    { number: 5,  position: 'DF', name: 'Aurele Amenda',         club: 'Eintracht Frankfurt' },
    { number: 6,  position: 'DF', name: 'Eray Comert',           club: 'Valencia' },
    { number: 7,  position: 'DF', name: 'Nico Elvedi',           club: 'Borussia Monchengladbach' },
    { number: 8,  position: 'DF', name: 'Luca Jaquez',           club: 'Stuttgart' },
    { number: 9,  position: 'DF', name: 'Miro Muheim',           club: 'Hamburg' },
    { number: 10, position: 'DF', name: 'Ricardo Rodriguez',     club: 'Real Betis' },
    { number: 11, position: 'DF', name: 'Silvan Widmer',         club: 'Mainz' },
    { number: 12, position: 'MF', name: 'Michel Aebischer',      club: 'Pisa' },
    { number: 13, position: 'MF', name: 'Christian Fassnacht',   club: 'Young Boys' },
    { number: 14, position: 'MF', name: 'Remo Freuler',          club: 'Bologna' },
    { number: 15, position: 'MF', name: 'Ardon Jashari',         club: 'AC Milan' },
    { number: 16, position: 'MF', name: 'Johan Manzambi',        club: 'Freiburg' },
    { number: 17, position: 'MF', name: 'Fabian Rieder',         club: 'Augsburg' },
    { number: 18, position: 'MF', name: 'Djibril Sow',           club: 'TBD' },
    { number: 19, position: 'MF', name: 'Ruben Vargas',          club: 'Sevilla' },
    { number: 20, position: 'MF', name: 'Granit Xhaka',          club: 'Sunderland' },
    { number: 21, position: 'MF', name: 'Denis Zakaria',         club: 'Monaco' },
    { number: 22, position: 'FW', name: 'Zeki Amdouni',          club: 'Burnley' },
    { number: 23, position: 'FW', name: 'Breel Embolo',          club: 'Stade Rennais' },
    { number: 24, position: 'FW', name: 'Cedric Itten',          club: 'Fortuna Dusseldorf' },
    { number: 25, position: 'FW', name: 'Dan Ndoye',             club: 'Nottingham Forest' },
  ],
};

export { SQUADS };
